[book]
authors = ["St Maxwell", "Euler-37", "左志华"]
language = "zh"
multilingual = false
src = "src"
title = "Fortran 语言实战"   # version = 0.1.0

[output.html]
git-repository-url = "https://github.com/fortran-fans/Fortran-in-Action/tree/main/"
edit-url-template = "https://github.com/fortran-fans/Fortran-in-Action/edit/main/{path}"
